server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P12A301?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF8
    username: S10P12A301@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: BG2SESN4XA
  jpa:
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
cloud:
  aws:
    credentials:
      access-key: AKIAT23F3XWNRKCFWFQZ
      secret-key: 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
    s3:
      bucket: togeduck
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
decorator:
  datasource:
    p6spy:
      enable-logging: true
